# Generated by Django 5.1.2 on 2024-11-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_consumption',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
